import os

from dotenv import load_dotenv

load_dotenv()

OPENAI_SECRET_KEY = os.getenv("OPENAI_API_KEY")
STABILITY_API_KEY = os.getenv("STABILITY_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GOOGLE_ENGINE_ID = os.getenv("GOOGLE_ENGINE_ID")
CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
REPLICATE_API_KEY = os.getenv("REPLICATE_API_KEY")
NEWS_API_KEY = os.getenv("NEWS_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
GNOSIS_RPC_URL = os.getenv("GNOSIS_RPC_URL")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
SERPER_API_KEY = os.getenv("SERPER_API_KEY")
DUNE_API_KEY = os.getenv("DUNE_API_KEY")
ALCHEMY_API_KEY = os.getenv("ALCHEMY_API_KEY")
EXCHANGE_API_KEY = os.getenv("EXCHANGE_API_KEY")
EXCHANGE_API_SECRET = os.getenv("EXCHANGE_API_SECRET")
